---
- name: registry test
  hosts: 192.168.1.80

  tasks:
  - name: Build and push an image using username and password
    containers.podman.podman_image:
      name: localhost/ansible_aut 
      push: yes
      username: user
      password: test
      push_args:
        dest: 192.168.1.80:5000/ansible_aut
