---
- name: restart gitlab
  hosts: loki4
  tasks:

    - name: Touch a file, using symbolic modes to set the permissions (equivalent to 0644)
      ansible.builtin.file:
        path: ~/foo.txt
        state: touch
      notify:
      - Restart apache

    - name: Ensure apache is running
      ansible.builtin.service:
        name: sshd
        state: started

  handlers:
    - name: Restart apache
      ansible.builtin.service:
        name: sshd
        state: restarted
